---

  - name: CURL docker shell script
    shell:
      chdir: /home/ubuntu
      cmd: curl -fsSL https://get.docker.com -o get-docker.sh
  - name: Execute docker shell script
    shell:
      chdir: /home/ubuntu
      cmd: sh get-docker.sh
  - name: Ensure docker group is created
    group:
      name: docker
      state: present
  - name: Add '{{ user }}' user to group docker
    user:
      name: '{{ user }}'
      groups: docker
      append: yes
  - name: Install Docker compose
    apt:
      name: docker-compose
      update_cache: yes
  - name: Create docker folder in ubuntu home folder along with subdirectories
    file:
      path: "{{ item }}"
      sate: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775
    loop:
      - /home/ubuntu/docker
      - /home/ubuntu/docker/products
      - /home/ubuntu/docker/website
  - name: Copy Docker-compose file to docker folder
    copy:
      src: files/docker-compose.yaml
      dest: /home/ubuntu/docker
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
  - name: Copy index file to docker/website folder
    copy:
      src: files/index.php
      dest: /home/ubuntu/docker/website
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
  - name: Copy dockerfile, requirements and api file to docker/products folder
    copy:
      src: files/{{item}}
      dest: /home/ubuntu/docker/products
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    with_items:
      ['api.py', 'requirements.py', 'Dockerfile']
